import uuid
from datetime import datetime

from pydantic import BaseModel


class QuestionOut(BaseModel):
    id: int
    question_number: int
    question_type: str
    question_text: str
    options: list[str] | None

    model_config = {"from_attributes": True}


class QuizOut(BaseModel):
    id: uuid.UUID
    session_id: uuid.UUID
    total_questions: int
    status: str
    questions: list[QuestionOut]

    model_config = {"from_attributes": True}


class AnswerItem(BaseModel):
    question_id: int
    answer: str  # 'A'/'B'/'C'/'D'


class AnswerSubmit(BaseModel):
    answers: list[AnswerItem]


# ── Admin-facing result (no scores, just Q&A record) ─────────────────────────

class QuestionAnswer(BaseModel):
    """One question + student's answer, returned to admin for review."""
    question_id: int
    question_number: int
    question_text: str
    options: list[str] | None
    student_answer: str        # what the student selected
    reference_answer: str      # expected answer generated by LLM
    admin_note: str | None     # explanation from LLM (why this answer matters)


class QuizSubmissionOut(BaseModel):
    """Full Q&A record stored after student submits the questionnaire."""
    attempt_id: uuid.UUID
    quiz_id: uuid.UUID
    submitted_at: datetime
    answers: list[QuestionAnswer]


# Keep legacy alias so existing imports don't break during transition
QuestionResult = QuestionAnswer
QuizResult = QuizSubmissionOut
